apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "http-load-tester.fullname" .}}
  namespace: {{ .Values.namespace.name }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
    {{- include "http-load-tester.selectorLabels" . | nindent 4 }}