{{- $namespace := .Values.namespace.name }}
{{- $fullname := include "http-load-tester.fullname" .}}
{{- $serviceHttpPort := .Values.service.port }}
{{- if and (eq (.Values.ingress.type | lower) "istio") (.Values.ingress.enabled) }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "http-load-tester.fullname" .}}
  labels: {{ include "http-load-tester.labels" . | nindent 4}}
  namespace: {{ .Values.namespace.name }}
spec:
  gateways:
    - {{ if .Values.ingress.gateway.namespace}}{{.Values.ingress.gateway.namespace }}/{{ end }}{{ .Values.ingress.gateway.name }}
  hosts:
  {{- range $host := .Values.ingress.hosts }}
    - {{ $host.host | quote }}
  http:
  {{- range $path := $host.paths }}
  - name: {{ .name }}
    match:
      - uri:
          prefix: {{ .hostRoute }}
    {{- if and (.serviceRoute) (ne .hostRoute .serviceRoute) }}
    rewrite:
      uri: {{ .serviceRoute }}
    {{- end }}
    route:
      - destination:
          host: {{$fullname}}.{{$namespace}}.svc.cluster.local
          port:
            number: {{ $serviceHttpPort }}
{{- end }}
{{- end }}
{{- end }}