name: PR Builder

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: PR Build and Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: [ 'go' ]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Install Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.8.1

    - name: Build
      working-directory: src
      run: go build -v ./...

    - name: Test
      working-directory: src
      run: go test -v ./...
    
    - name: Helm Chart Lint
      run: |
        helm lint ./charts